# Generated by Django 3.2.9 on 2021-11-17 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biddingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='hosted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4e662aeb-3a82-4991-95e9-c131998c4be6'), editable=False, unique=True),
        ),
    ]
