# Generated by Django 3.2.9 on 2021-11-17 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biddingApp', '0002_auto_20211117_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('84371d5a-e1b6-41a5-9668-2cfeef691235'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bidder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
